name: Email Test Workflow

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f2001559@ds.study.iitm.ac.in
        run: echo "Hello from GitHub Actions!"
